name: Markdown spell check

on:
  pull_request:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  spell-check:
    runs-on: ubuntu-latest
    name: Markdown spell check
    steps:
    - name: Markdown spell check
      aspell:
        lang: en
      dictionary:
        wordlists:
        - .wordlist.txt
        encoding: utf-8
      pipeline:
      - pyspelling.filters.markdown:
      - pyspelling.filters.html:
        comments: false
        ignores:
        - code
        - pre
      sources:
      - '**/*.md'
      default_encoding: utf-8