name: Auto Label
on:
  pull_request:
    types: [opened, labeled]

jobs:
  auto-label:
    name: Auto Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: banyan/auto-label@1.2
      - uses: shufo/auto-assign-reviewer-by-files@v1.0.0
      with:
        config: '.github/assign-by-files.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}